# Generated by Django 5.0.1 on 2024-01-27 05:14

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('set_is_active', 'Может блокировать пользователя')]},
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone',
            field=models.BooleanField(choices=[(True, 'Активен'), (False, 'Неактивен')], default=True, verbose_name='телефон проверен'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.CharField(blank=True, default=models.CharField(blank=True, default='898161533938', max_length=50, null=True, verbose_name='проверочный код'), max_length=50, null=True, verbose_name='проверочный код телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='898161533938', max_length=50, null=True, verbose_name='проверочный код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=150, null=True, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Активен'), (False, 'Неактивен')], default=True, verbose_name='почта проверена'),
        ),
    ]
