# Generated by Django 5.0.1 on 2024-01-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_code_alter_user_phone_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, default='506969847825', max_length=50, null=True, verbose_name='проверочный код'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_verified',
            field=models.CharField(blank=True, default=models.CharField(blank=True, default='506969847825', max_length=50, null=True, verbose_name='проверочный код'), max_length=50, null=True, verbose_name='проверочный код телефона'),
        ),
    ]
