# Generated by Django 5.0.1 on 2024-02-03 15:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='отчество')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='контактный email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('comments', models.TextField(verbose_name='комментарии')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('last_name', 'first_name', 'patronymic'),
                'permissions': [('client_delete', 'Может удалять клиентов')],
            },
        ),
        migrations.CreateModel(
            name='MailingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test', max_length=50, verbose_name='наименование рассылка')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='начало рассылки')),
                ('next_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='следующая рассылка')),
                ('finish_date', models.DateTimeField(verbose_name='завершение рассылки')),
                ('frequency', models.CharField(choices=[('ONCE', 'разовая'), ('DAY', 'раз в день'), ('WEEK', 'раз в неделю'), ('MONTH', 'раз в месяц')], default='ONCE', max_length=15, verbose_name='периодичность')),
                ('status', models.CharField(choices=[('FINISH', 'завершена'), ('CREATE', 'создана'), ('START', 'запущена')], default='CREATE', max_length=100, verbose_name='статус')),
                ('is_activated', models.BooleanField(choices=[(True, 'Активна'), (False, 'Неактивна')], default=True, verbose_name='Активность')),
                ('clients', models.ManyToManyField(blank=True, to='mailing_service.client', verbose_name='получатели')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('start_date',),
            },
        ),
        migrations.CreateModel(
            name='LogsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата и время отправки')),
                ('status', models.CharField(blank=True, choices=[('Success', 'успешно'), ('Failure', 'отказ')], max_length=50, null=True, verbose_name='статус попытки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing_service.mailingsetting', verbose_name='лог рассылки')),
            ],
            options={
                'verbose_name': 'лог рассылки',
                'verbose_name_plural': 'логи рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='тема рассылки')),
                ('body', models.TextField(verbose_name='тело рассылки')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец сообщения')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='mailingsetting',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing_service.message', verbose_name='сообщение'),
        ),
    ]
