# Generated by Django 5.0 on 2023-12-24 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='имя')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='отчество')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='контактный email')),
                ('comments', models.TextField(verbose_name='комментарии')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
                'ordering': ('last_name', 'first_name', 'patronymic'),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='тема рассылки')),
                ('body', models.TextField(verbose_name='тело рассылки')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='MailingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='время рассылки')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('frequency', models.CharField(choices=[('DAY', 'раз в день'), ('WEEK', 'раз в неделю'), ('MONTH', 'раз в месяц')], max_length=100, verbose_name='периодичность')),
                ('status', models.CharField(choices=[('FINISH', 'завершена'), ('CREATE', 'создана'), ('START', 'запущена')], max_length=100, verbose_name='статус')),
                ('finish_date', models.DateField(default='2024-01-01', verbose_name='дата завершения рассылки')),
                ('finish_time', models.TimeField(default='00:00', verbose_name='время завершения рассылки')),
                ('client', models.ManyToManyField(blank=True, to='mailing_service.client', verbose_name='клиент')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing_service.message', verbose_name='сообщение')),
            ],
            options={
                'verbose_name': 'настройка рассылки',
                'verbose_name_plural': 'настройки рассылок',
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='LogsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='дата и время отправки')),
                ('status', models.CharField(choices=[('Success', 'успешно'), ('Failure', 'отказ')], max_length=50, verbose_name='статус попытки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing_service.mailingsetting', verbose_name='лог рассылки')),
            ],
            options={
                'verbose_name': 'лог рассылки',
                'verbose_name_plural': 'логи рассылки',
            },
        ),
    ]
