# Generated by Django 5.0.1 on 2024-01-27 06:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('last_name', 'first_name', 'patronymic'), 'permissions': [('client_delete', 'Может удалять клиентов')], 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailingsetting',
            options={'ordering': ('start_date',), 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.RemoveField(
            model_name='mailingsetting',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='mailingsetting',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='mailingsetting',
            name='time',
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='отправитель'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='mailingsetting',
            name='is_activated',
            field=models.BooleanField(choices=[(True, 'Активна'), (False, 'Неактивна')], default=True, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='mailingsetting',
            name='name',
            field=models.CharField(default='test', max_length=50, verbose_name='наименование рассылка'),
        ),
        migrations.AddField(
            model_name='mailingsetting',
            name='next_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='следующая рассылка'),
        ),
        migrations.AddField(
            model_name='mailingsetting',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец рассылки'),
        ),
        migrations.AddField(
            model_name='mailingsetting',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='начало рассылки'),
        ),
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец сообщения'),
        ),
        migrations.AlterField(
            model_name='mailingsetting',
            name='client',
            field=models.ManyToManyField(blank=True, to='mailing_service.client', verbose_name='получатели'),
        ),
        migrations.AlterField(
            model_name='mailingsetting',
            name='finish_date',
            field=models.DateTimeField(verbose_name='завершение рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsetting',
            name='frequency',
            field=models.CharField(choices=[('ONCE', 'разовая'), ('DAY', 'раз в день'), ('WEEK', 'раз в неделю'), ('MONTH', 'раз в месяц')], default='ONCE', max_length=15, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailingsetting',
            name='status',
            field=models.CharField(choices=[('FINISH', 'завершена'), ('CREATE', 'создана'), ('START', 'запущена')], default='CREATE', max_length=100, verbose_name='статус'),
        ),
    ]
