# Generated by Django 5.0.1 on 2024-01-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0002_alter_client_options_alter_mailingsetting_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailingsetting',
            old_name='client',
            new_name='clients',
        ),
        migrations.AlterField(
            model_name='logsmessage',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата и время отправки'),
        ),
        migrations.AlterField(
            model_name='logsmessage',
            name='status',
            field=models.CharField(blank=True, choices=[('Success', 'успешно'), ('Failure', 'отказ')], max_length=50, null=True, verbose_name='статус попытки'),
        ),
    ]
